# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [77]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [78]:
print(np.__version__)
np.show_config()

2.4.2
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.2.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/xx/pgt1mtfn3xx3hdys7czt35bh0000gn/T/build-env

#### 3. Create a null vector of size 10 (★☆☆)

In [79]:
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [80]:
sample_array = np.array([[1,2,3],[4,5,6]])
print(sample_array.dtype) 
print(sample_array.shape) 

sample_arr_float = sample_array.astype('float64')
print(sample_arr_float, sample_arr_float.dtype)

int64
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]] float64


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [81]:
array = np.zeros(10)
array[4] = 1
print(array)
     

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [82]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [83]:
reverse_vector = vector[::-1]
print(reverse_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [84]:
array = np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [85]:
array = np.array([1,2,0,0,4,0])
array1 = array[array != 0]
print(array1)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [86]:
array1 = np.identity(3)
print(array1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [87]:
array_random = np.random.random((3,3,3))
print(array_random)

[[[0.98810909 0.74000168 0.1463947 ]
  [0.94368798 0.29768254 0.65260536]
  [0.40403547 0.79250753 0.9403943 ]]

 [[0.47857633 0.24184526 0.13463524]
  [0.76947008 0.31683704 0.61201121]
  [0.5997487  0.25560282 0.5162509 ]]

 [[0.93371328 0.76962942 0.16521269]
  [0.89511838 0.73287044 0.94266734]
  [0.98319797 0.69845716 0.10195742]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [88]:
array2 = np.random.random((10,10))
print(array2.min())
print(array2.max())

0.0083435995473915
0.9828588540301416


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [89]:
vector = np.random.random(30)
print(vector.mean())

0.4749717824965606


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [90]:
array2d = np.ones((5,5))
print(array2d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [91]:
array3 = np.diag(np.arange(1,5),k=-1)
print(array3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [92]:
array4 = np.zeros((8,8))
array4[::2, 1::2] = 1 
array4[1::2, ::2] = 1
print(array4)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [93]:
print(np.unravel_index(100, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [94]:
Z = np.random.random((5,5))
Z = (Z - Z.mean()) / Z.std()
print(Z)

[[ 1.11573142  0.54283766 -0.8940584   1.68937646  0.41704755]
 [ 1.86235118 -0.80136871 -1.1280575  -0.43680469 -0.40124455]
 [-1.0117278  -1.32020521  1.14273189  0.38956382 -1.66641473]
 [ 0.74753613 -0.62914047  0.41768302 -1.24670072  0.47871353]
 [ 0.63824809 -1.16141598  0.43478973 -0.51246201  1.3329903 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [95]:
color = np.dtype([
    ("R", np.ubyte),
    ("G", np.ubyte),
    ("B", np.ubyte),
    ("A", np.ubyte)
])

print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [96]:
array1 = np.random.random((5,3))
array2 = np.random.random((3,2))

array3 = np.dot(array1, array2)

print(array3)

[[0.79233484 0.24979719]
 [1.04968017 0.4274518 ]
 [1.51396506 0.53062975]
 [0.47418296 0.07552556]
 [1.27554345 0.42550012]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [97]:
array1 = np.arange(10)

array1[(array1 > 3) & (array1 < 8)] *= -1

print(array1)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [98]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [99]:
Z = np.array([1,2,3])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z  #이게 틀린거


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)           #nan
np.array(0) // np.array(0)          #0
np.array([np.nan]).astype(int).astype(float)      #오    

/var/folders/qq/ztxvnh1179n6zkv1p29yx6nh0000gn/T/ipykernel_4526/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/qq/ztxvnh1179n6zkv1p29yx6nh0000gn/T/ipykernel_4526/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/qq/ztxvnh1179n6zkv1p29yx6nh0000gn/T/ipykernel_4526/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)

print(np.intersect1d(array1,array2))

[1 2 4 5 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) #False

/var/folders/qq/ztxvnh1179n6zkv1p29yx6nh0000gn/T/ipykernel_4526/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
array1 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(array1)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)

[7. 8. 1. 0. 1. 4. 7. 7. 7. 1.]
[7. 8. 1. 0. 1. 4. 7. 7. 7. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array1 = np.random.random(10)

array1.sort()

print(array1)

[0.08615215 0.125251   0.22387281 0.28017422 0.47068508 0.79420579
 0.81579748 0.83705149 0.88039557 0.97480915]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

array1 = np.array_equal(A,B)
print(array1)


False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.37711235 1.19073752 0.43256295 1.24792721 1.14862859 0.67663282
 0.86922603 0.2614698  0.93472819 0.96959397]
[0.76398804 0.76459255 0.29220529 0.65540642 0.99948838 0.35254152
 1.57063146 0.86494204 0.55413354 0.1159457 ]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.37288199 0.17520528 0.28163025 0.04549415 0.70829903 0.
 0.01518433 0.39042962 0.61857878 0.57732584]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()   
print(Z[index])

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 5
p = 5

Z = np.zeros((n,n))

np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

print(Z)

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [104]:
# column 3
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[6 0 9]
 [4 9 7]
 [9 9 5]]
[[4 9 7]
 [6 0 9]
 [9 9 5]]


In [105]:
# column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[6 0 9]
 [4 9 7]
 [9 9 5]]
[[6 0 9]
 [4 9 7]
 [9 9 5]]


In [106]:
# column 3
Z = Z.reshape(-1,3)

print(Z)
print(Z[Z[:,2].argsort()])

[[6 0 9]
 [4 9 7]
 [9 9 5]]
[[9 9 5]
 [4 9 7]
 [6 0 9]]
