# Chapter 1

넘파이(NumPy) 
- Numerical Python을 의미
- 파이썬에서 선형대수 기반 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
- C/C++등의 언어 기반의 호환 API 제공 

넘파이 장점 
- 매우 빠른 배열 연산 보장

##### 넘파이 ndarray 개요
- 넘파이의 기반 데이터 타입 : ndarray (이를 통해 넘파이에서 다차원 배열을 쉽게 생성하고 연산 수행 가능
)
- array() : 다양한 인자를 입력받아 ndarray로 변환하는 기능을 수행 

In [35]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])                      # 1차원 3개의 데이터  
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],                     # 2차원 6개의 데이터  
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])               
print('array3 type:', type(array3))        
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [37]:
print('array1:{:0}차원,array2:{:1}차원, array3:{:2}차원'.format(array1.ndim, array2.ndim, array3.ndim)) #ndarray.ndim을 이용해 각 array의 차원 확인 가능 

array1:1차원,array2:2차원, array3: 2차원


##### ndarray의 데이터 타입
- ndarray내 데이터 값 : 숫자 값, 문자열 값, 불 값 등 모두 가능 
- 같은 데이터 타입만 가능 : dtype 속성으로 확인 가능 

In [38]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(array1, array1.dtype)          #integer 1,2,3을 값으로 가지고 있고, ndarray로 변경된 데티어 값은 모두 int64형이다


<class 'list'>
[1 2 3] int64


만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경 --> 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용시킨다. 

In [39]:
# int, string
list2 = [1,2, 'test']   #숫자형 값 1,2가 문자열 값인 '1' '2'로 변경
array2 = np.array(list2)
print(array2, array2.dtype)

# int, float
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)


['1' '2' 'test'] <U21
[1. 2. 3.] float64


ndarray 내 데이터 값의 타입 변경 : astype()을 이용해서 할 수 있다.
astype()에 인자로 원하는 타입을 문자열로 지정 
- 이렇게 변경할 경우 대용량 데이터에서 메모리 절약 할 때 이용

In [40]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')  #int32 -> float64
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')   #float64 -> int32
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')   #float->int (소수점 이하 사라짐)

[1. 2. 3.] float64
[1 2 3] int32


##### ndarray를 편리하게 생성하기 - arrange, zeos, ones
arrange(), zeros(), ones() - 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우
- 주로 테스트용 데이터 만들때, 혹은 대규모 데이터를 일괄적으로 초기화 할 경우 사용

In [41]:
# arange()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [42]:
# defult 함수 인자 : stop값, 0~stop값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만들어준다

# zero() : 튜플 형태의 shape를 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray로 반환
# ones() : 튜플 형태의 shape를 입력하면 모든 값을 1으로 채운 해당 shape를 가진 ndarray로 반환
# 함수 인자로 dtype 정해주지 않을시, defult로 float64형태 데이터로 ndarray를 채운다

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


##### ndarray의 차원과 크기를 변경하는 reshape()
reshape() : ndarray를 특정 차원 및 크기로 변환한다
- 인자 : 변환을 원하는 크기를 함수 인자로 부여

In [43]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [44]:
# 단 지정 사이즈로 변경이 불가능하면 오류가 발생한다
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

reshape()를 효율적으로 사용하는 경우 : -1을 적용하는 경우
- -1를 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 준다. 

In [ ]:
array1 = np.arange(10)              
print(array1)
array2 = array1.reshape(-1,5)             #array2는 로우 인자가 -1, 칼럼 인자가 5
print('array2.shape:', array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2.shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

- reshape(-1,1) : 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다
- 여러 개의 넘파이 ndarray는 stack이나 concat으로 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용
- tolist() 매서드를 사용해 리스트 자료형으로 변환 가능

In [ ]:

array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:/n',array6.tolist())
print('array6 shape:',array6.shape)
     

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:/n [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


##### 인덱싱(Indexing)
- 특정 데이터만 추출
- 슬라이싱(slicing) : '.' 기호 사이에 인덱스 표시하면 시작인덱스에서 종료인덱스 -1 위치에 있는 데이터의 ndarray를 반환한다
- 팬시 인덱싱(fancy indexing) :  일정 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 테이터의 ndarray를 반환한다
- 불린 인덱싱 (boolean indexing) : 특정 조건에 해당하는지 (t/f) 값 인덱싱 집합을 기반으로 true에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환한다


단일 값 추출 : 1개의 데이터 값 선택 : ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력한다

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


다차원 ndarray에서 단일 값 추출 
==> 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근

In [ ]:

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


axis 0, axis 1
axis 0 : 로우 방향의 축
axis 1 : 칼럼 방향의 축
- 다차원 ndarray에서는 축에 따른 연산을 지원한다
- axis가 생략되면 axis 0을 의미한다

슬라이싱
':' : 연속한 데이터를 슬라이싱해 추출할 수 있다
- 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1의 위치에 있는 데이터의 ndarray를 반환한다
1. ‘：’ 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주합니다
2. ‘:’ 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주합니다
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주한다


In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다.
2차원 --> 1차원 반환
3차원 --> 2차원 반환


In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


팬시 인덱싱 
: ndarray로 인덱스 집합을 지정시, 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>',array3.tolist())

array4 = array2d[[0,1],0:2]
print('array2d[[0,1],0:2] =>',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>',array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1],0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


불린 인덱싱 
- 자주 사용됨
- 조건 필터링과 검색을 동시에 수행 가능

for loop/if else문보다 훨씬 간단하게 구현 가능
- []내의 조건문을 그대로 기재하면 된다

동작 단계 도식화
1. array1d>5과 같이 ndarray의 필터링 조건을 []안에 기재
2. false값은 무시하고 true값에 해당하는 인덱스값만 저장 (true값 1을 저장하는 것이 아님)
3. 저장된 인덱스 데이터 세트로 ndarray 조회

In [ ]:
array1d = np.arange(start=1, stop=10)
# []안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :',array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d >5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


##### 행렬의 정렬 - sort(), argsort()
- np.sort()
- ndarray.sort()
- argsort()

행렬 정렬
- np.sort() : 왼 행렬을 유지한 채 원 행렬의 정렬된 행렬을 반환
- ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None


In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:',org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:',sort_array1)
print('np.sort() 호출 후 원본 행렬:',org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)

# 모두 기본적으로 오름차순으로 행렬 내 원소 정렬

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [46]:
# 내림 차순 정렬은 [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
# 2차원 이상의 행렬인 경우 axis 축 값 설정을 통해 로우, 칼럼 방향으로 정렬 수행 가능

array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


정렬된 행렬의 인덱스를 반환하기
- 기존 원본 행렬의 우너소에 대한 인덱스를 필요로 할 때 : np.argsort()를 이용한다
- argsort()는 넘파이에서 활용도가 높다

In [48]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [49]:
# 내림차순 [::-1] 적용

org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬시 원본 행렬의 인덱스:',sort_indices_desc)

행렬 내림차순 정렬시 원본 행렬의 인덱스: [2 3 0 1]


In [50]:
import numpy as np

name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


##### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
행렬 내적 (행렬 곱)
- 두 행렬 A, B의 내적은 np.dot()을 이용해 계산 가능


In [51]:
A = np.array( [[1,2,3],
               [4,5,6]])
B = np.array( [[7,8],
               [9,10],
               [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n',dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


전치 행렬
- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
- A' transpose와 같다
- transpose()를 이용

In [52]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
